### ISSUE TITLE
Bug in online simulator

### ISSUE THREAD

**Issue by LukeGary462** [Omega-Numworks/Omega#485] opened 2021-02-22 23:03 UTC
I am evaluating the Omega OS on the online emulator to see if the behavior is different, but it gives a similar error to epsilon documented [here](https://github.com/numworks/epsilon/issues/1780)

![image](https://user-images.githubusercontent.com/7936358/108781547-0c4e2b80-7538-11eb-8615-105f54f8e2d8.png)

the same calculation on wolfram yields the correct answer, pi
![image](https://user-images.githubusercontent.com/7936358/108781711-4f100380-7538-11eb-83ab-1f437ae75aa3.png)

**Comment by LukeGary462** [comment] 2021-02-22 23:07
Corrected Denominator does not fix the issue either (error in my original screenshot)
![image](https://user-images.githubusercontent.com/7936358/108782026-d2c9f000-7538-11eb-8ca9-22bb2442589c.png)

**Comment by quentinguidee** [comment] 2021-02-22 23:08
Hi! Thank you for this issue

In fact, in Omega, we don't fix issues caused by upstream. So, if the issue appears on Epsilon, it should be fixed on Epsilon first and then we'll integrate the fix in Omega. So, I'll close this issue. Feel free to comment if you think I misunderstood the problem!

**Closed by quentinguidee** 2021-02-22 23:08 UTC
Labels: Type: Upstream issue

**Comment by LukeGary462** [comment] 2021-02-23 14:48
ok, I was just a little confused. Omega is claiming symbolic math support, and a solution to this expression seems to be covered under that feature.

**Comment by RedGl0w** [comment] 2021-02-23 14:51
> ok, I was just a little confused. Omega is claiming symbolic math support, and a solution to this expression seems to be covered under that feature.

Indeed, symbolic is not CAS most of the time
We have the same type of feature for derivation, but not for integration :/

**Comment by LukeGary462** [comment] 2021-02-23 15:37
so I also just checked this with KhiCAS and it solves the expression correctly on the demo page
https://www-fourier.univ-grenoble-alpes.fr/~parisse/numworks/khicasnw.html#sec2

![msedge_UKPGzMDBH7](https://user-images.githubusercontent.com/7936358/108867303-0f422e00-75c3-11eb-92fb-619c5a85d721.png)

But unfortunately this cannot be installed on the N0100 model as far as I know.

**Comment by RedGl0w** [comment] 2021-02-23 15:39
> But unfortunately this cannot be installed on the N0100 model as far as I know.

Khicas is about 4mb
N0100 has 1mb
It's physically impossible yes
