### ISSUE TITLE
Softlock in python app 

### ISSUE THREAD

**Issue by Moddingear** [Omega-Numworks/Omega#303] opened 2020-03-06 14:01 UTC
#### Describe the bug
When looping in python, with a Kandinsky window displayed and while using ion, the calculator will sometimes softlock, causing the calculator to not respond to any input except the reset button, loosing anything stored on the calculator. I don't know if Kandinsky or python are needed. 

#### Environment
 - Omega Version: O1.19.0
 - Model : n0100

**Comment by quentinguidee** [comment] 2020-03-21 10:38
Hi! Thank you for this issue!

First of all, I think this issue is fixed on Omega 1.19.1. Could you try it and say me if it's fixed ? :)

If I understood the issue correctly, this bug came from Epsilon 13 Beta and is not caused by Omega. We reported this bug to Numworks™ which has since fixed it.

**Comment by quentinguidee** [comment] 2020-03-22 23:07
I close this issue, feel free to comment if it's not fixed.

**Closed by quentinguidee** 2020-03-22 23:07 UTC
Labels: Bug, In investigation
