### ISSUE TITLE
Keep backspace operation in alpha mode

### ISSUE THREAD

**Issue by AlexPMLikesNumWorks** [Omega-Numworks/Omega#56] opened 2019-11-07 14:26 UTC
**What I want to see in the next version of Omega**

One of the most annoying "features" of the N0110 is the percent sign asigned to the backspace key in alpha mode. Backspqce operation (deleting the character on le left) is much more useful than percent insertion, thus the backspace should not be affected by the alpha mode.

I would suggest to "move" the percent sign in alpha mode to the x10^x key at the bottom, or to remove it completely as in the N0100.

More generally, the bottom keys could be used in combination with the shift modifier (out of alpha mode) to input various exotic characters like %, #, ^, etc. (these are usually indirectly available through the toolbox menu).

**Comment by RedGl0w** [comment] 2019-11-07 16:28
This issue isn't only on n0110, on n0100 it appears also. 
going to correct it this evening

**Comment by quentinguidee** [comment] 2019-11-07 16:30
**Note:** Duplicate of https://github.com/numworks/epsilon/issues/1186

**Comment by AlexPMLikesNumWorks** [comment] 2019-11-07 16:39
Yes it was me too ;-)
Not sure they (NumWorks) will accept it, because the % is present on their hardware.
But Omega can be free of this consideration.

**Comment by quentinguidee** [comment] 2019-11-07 16:55
Our goal is also to keep the calculator as simple as Numworks does, but we want to listen to the community as much as possible. So, we're looking for a way to solve this issue without loosing the ease of use. If we remove the % of the backspace key, we'll receive bugs reports like "oh the % sign don't work on n0110"; so with Redgl0w we think of a setting or something like this... But we're not yet convinced.... So don't worry we'll find a solution very soon ^^

**Comment by quentinguidee** [comment] 2019-11-17 13:53
![](https://github.trello.services/images/mini-trello-icon.png) [Keep backspace operation in alpha mode](https://trello.com/c/GRu31KVq/16-keep-backspace-operation-in-alpha-mode)

**Comment by RedGl0w** [comment] 2019-12-22 07:28
I think the simplest solution is to disable percent, and to make it remove the last character.
If you need to add a percent (which you only need on python), the shortcut in the toolbox is very quick to access. I will just add an options to choose if you want to be able to add percent by the key, or not.

**Comment by RedGl0w** [comment] 2019-12-23 20:15
https://github.com/Omega-Numworks/Omega/issues/102#issuecomment-568571283
Now this issue can be closed

**Closed** 2019-12-24 16:42 UTC
Labels: Feature
